### ISSUE TITLE
Allow downloading from nested fields

### ISSUE THREAD

**Issue by hacknug** [noxify/gridsome-plugin-remote-image#3]
The way `sourceField` is currently used, prevents us from downloading images in nested fields. [LokiJS seems to support using dot notation](https://github.com/techfort/LokiJS/blob/f7acb98a4129845bbd2c9aa23e5ed4a10ee75ce8/examples/quickstart-core.js#L73) to access nested fields so it would be great if the plugin didn't expect that to be a top-level field.

**Comment by noxify** [comment]
Hi @hacknug,

I will take a look.

But before changing something, i have a question to make sure we're talking about the same.

> We're not talking about dot walking in relationships

My opinion is, that dot walking and downloading the image from a reference makes no sense.
Here i recommend to create a new definition for the referenced collection

----

I assume you mean something like this:

```
---
title: Markdown test file with local file
tags: ['Markdown','Test files']
nested:
  - sub:
    - sub1: https://url.tld/image.jpg
---

## Content
```

This means, when an user defines something like this:
```
{
      use: '@noxify/gridsome-plugin-image-download',
      options: {
        'typeName' : 'Entry',
        'sourceField': 'nested.sub.child',
        'targetField': 'imagesDownloaded',
        'targetPath': './src/assets/remoteImages'
      }
    }
```
They have to ensure that the field is not a reference.

----

Is this correct?

Thanks!

Regards,
Marcus
